name: Infra + App Deploy (Terraform + ECS, OIDC)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      action:
        description: "Set to 'destroy' to tear down the stack"
        required: false
        default: ""
        type: string

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 097635932419.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: myapp
  CLUSTER_NAME: docker-ecs-deployment-cluster
  SERVICE_NAME: docker-ecs-deployment-svc
  IMAGE_TAG: latest
  IMAGE_SHA_TAG: ${{ github.sha }}
  TF_WORKING_DIR: infra

permissions:
  id-token: write   # Needed for OIDC
  contents: read

concurrency:
  group: infra-deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  # ===========================
  # 1) TERRAFORM: init/plan/apply or destroy
  # ===========================
  terraform:
    name: Terraform (init/plan/apply or destroy)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 👉 Широкая роль: ДОЛЖНА быть terraform-роль
      - name: Configure AWS for Terraform (broad role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::097635932419:role/github-actions-terraform-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Who am I (Terraform role)
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Cache Terraform dirs
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.TF_WORKING_DIR }}/.terraform
            ~/.terraform.d/plugin-cache
          key: tf-${{ runner.os }}-${{ hashFiles('**/*.tf', '**/*.tfvars', '**/.terraform.lock.hcl') }}

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_PLUGIN_CACHE_DIR: ~/.terraform.d/plugin-cache
          TF_LOG: INFO
          TF_IN_AUTOMATION: 1
        run: terraform init -input=false -upgrade -no-color

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_LOG: INFO
          TF_IN_AUTOMATION: 1
        run: terraform validate -no-color

      # Если вручную и action=destroy → выполнить destroy и завершить job
      - name: Terraform Destroy (manual)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.action == 'destroy' }}
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_LOG: INFO
          TF_IN_AUTOMATION: 1
        run: terraform destroy -auto-approve -no-color

      # Иначе обычный план/апплай
      - name: Terraform Plan
        if: ${{ !(github.event_name == 'workflow_dispatch' && inputs.action == 'destroy') }}
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_LOG: INFO
          TF_IN_AUTOMATION: 1
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Terraform Apply
        if: ${{ !(github.event_name == 'workflow_dispatch' && inputs.action == 'destroy') }}
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_LOG: INFO
          TF_IN_AUTOMATION: 1
        run: terraform apply -input=false -no-color -auto-approve tfplan

  # ===========================
  # 2) IMAGE & DEPLOY: build/push image + ECS update-service
  # ===========================
  image_and_deploy:
    name: Build & Push Image, ECS Deploy
    needs: terraform
    runs-on: ubuntu-latest
    if: ${{ !(github.event_name == 'workflow_dispatch' && inputs.action == 'destroy') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 👉 Узкая роль: ДОЛЖНА быть ecs-роль (ECR push + ECS update)
      - name: Configure AWS for Deploy (least-priv role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::097635932419:role/github-actions-ecs-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Who am I (Deploy role)
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image (latest + sha)
        run: |
          docker buildx create --use --name mybuilder || true
          # Dockerfile и контекст находятся в infra/
          docker buildx build --platform linux/amd64 \
            -f infra/Dockerfile infra \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_SHA_TAG \
            --push

      - name: Force new ECS deployment
        run: |
          aws ecs update-service \
            --cluster $CLUSTER_NAME \
            --service $SERVICE_NAME \
            --force-new-deployment \
            --region $AWS_REGION